Repository smu-nity/SMUNITY-API, pull requests merged in 2024-02, with the labels that each got.

#29 [REFACTOR] Q&A Dto 수정 및 로직 추가 (#27)
  src/main/java/com/smunity/graduation/domain/qna/controller/QuestionController.java
  src/main/java/com/smunity/graduation/domain/qna/dto/QuestionListResponseDto.java
  src/main/java/com/smunity/graduation/domain/qna/dto/QuestionResponseDto.java
  src/main/java/com/smunity/graduation/domain/qna/dto/QuestionsResponseDto.java
  src/main/java/com/smunity/graduation/domain/qna/service/AnswerService.java
  src/main/java/com/smunity/graduation/domain/qna/service/QnAServiceUtils.java
  src/main/java/com/smunity/graduation/domain/qna/service/QuestionService.java
  src/main/java/com/smunity/graduation/global/common/code/status/ErrorCode.java
Labels: ♻️ Refactor

#31 [Feature] UserDeatils 객체 수정 및 시큐리티 수정, SQL 파일 생성
  http/AccountsTest.http
  src/main/java/com/smunity/graduation/domain/accounts/annotation/AccountsArgumentResolver.java
  src/main/java/com/smunity/graduation/domain/accounts/entity/User.java
  src/main/java/com/smunity/graduation/domain/accounts/jwt/exception/SecurityFilterException.java
  src/main/java/com/smunity/graduation/domain/accounts/jwt/exception/status/TokenErrorCode.java
  src/main/java/com/smunity/graduation/domain/accounts/jwt/filter/CustomLoginFilter.java
  src/main/java/com/smunity/graduation/domain/accounts/jwt/filter/JwtExceptionFilter.java
  src/main/java/com/smunity/graduation/domain/accounts/jwt/filter/JwtFilter.java
  src/main/java/com/smunity/graduation/domain/accounts/jwt/util/HttpResponseUtil.java
  src/main/java/com/smunity/graduation/domain/accounts/jwt/util/JsonUtil.java
  src/main/java/com/smunity/graduation/domain/accounts/jwt/util/JwtUtil.java
  src/main/java/com/smunity/graduation/domain/accounts/jwt/util/ResponseUtil.java
  src/main/java/com/smunity/graduation/domain/course/entity/Course.java
  src/main/java/com/smunity/graduation/domain/graduation/dto/GraduationResponseDto.java
  src/main/java/com/smunity/graduation/global/common/exception/GeneralException.java
  src/main/java/com/smunity/graduation/global/config/SecurityConfig.java
  src/main/resources/application.yml
  src/main/resources/department.sql
  src/main/resources/year.sql
Labels: ✨ Feature

#32 [FEATURE] 기이수과목 API 작성 (#30)
  src/main/java/com/smunity/graduation/domain/accounts/entity/User.java
  src/main/java/com/smunity/graduation/domain/auth/dto/AuthCourseResponseDto.java
  src/main/java/com/smunity/graduation/domain/course/controller/CourseController.java
  src/main/java/com/smunity/graduation/domain/course/dto/CourseResponseDto.java
  src/main/java/com/smunity/graduation/domain/course/entity/Course.java
  src/main/java/com/smunity/graduation/domain/course/repository/CourseRepository.java
  src/main/java/com/smunity/graduation/domain/course/service/CourseQueryService.java
  src/main/java/com/smunity/graduation/domain/course/service/CourseService.java
  src/main/java/com/smunity/graduation/domain/graduation/dto/GraduationResponseDto.java
  src/main/java/com/smunity/graduation/domain/graduation/entity/Subject.java
  src/main/java/com/smunity/graduation/domain/graduation/repository/CourseTemporaryRepository.java
  src/main/java/com/smunity/graduation/domain/graduation/repository/SubjectRepository.java
  src/main/java/com/smunity/graduation/domain/graduation/service/GraduationService.java
  src/main/java/com/smunity/graduation/domain/graduation/temporary/CourseTemporary.java
  src/main/java/com/smunity/graduation/domain/graduation/utils/GraduationUtil.java
  src/main/java/com/smunity/graduation/domain/qna/entity/Answer.java
  src/main/java/com/smunity/graduation/domain/qna/entity/Question.java
  src/main/java/com/smunity/graduation/global/common/code/status/ErrorCode.java
  src/main/resources/sql/graduations_culture.sql
  src/main/resources/sql/graduations_major.sql
  src/main/resources/sql/graduations_subject.sql
Labels: ✨ Feature

#40 [FIX] Q&A 에러 해결
  src/main/java/com/smunity/graduation/domain/qna/service/QnAServiceUtils.java
Labels: 🐛 BugFix

#49 [FEATURE] Q&A 로그인 연동 (#44)
  src/main/java/com/smunity/graduation/domain/qna/controller/AnswerController.java
  src/main/java/com/smunity/graduation/domain/qna/controller/QuestionController.java
  src/main/java/com/smunity/graduation/domain/qna/dto/AnswerResponseDto.java
  src/main/java/com/smunity/graduation/domain/qna/entity/Answer.java
  src/main/java/com/smunity/graduation/domain/qna/entity/Question.java
  src/main/java/com/smunity/graduation/domain/qna/service/AnswerService.java
  src/main/java/com/smunity/graduation/domain/qna/service/QnAServiceUtils.java
  src/main/java/com/smunity/graduation/domain/qna/service/QuestionService.java
Labels: ✨ Feature

#46 [FEATURE] 기이수과목 API 로그인 연동 (#45)
  src/main/java/com/smunity/graduation/domain/auth/dto/AuthCourseResponseDto.java
  src/main/java/com/smunity/graduation/domain/course/controller/CourseController.java
  src/main/java/com/smunity/graduation/domain/course/dto/CourseRequestDto.java
  src/main/java/com/smunity/graduation/domain/course/dto/CourseResponseDto.java
  src/main/java/com/smunity/graduation/domain/course/entity/Course.java
  src/main/java/com/smunity/graduation/domain/course/repository/CourseRepository.java
  src/main/java/com/smunity/graduation/domain/course/service/CourseQueryService.java
  src/main/java/com/smunity/graduation/domain/course/service/CourseService.java
  src/main/java/com/smunity/graduation/domain/graduation/dto/GraduationResponseDto.java
  src/main/java/com/smunity/graduation/domain/graduation/dto/SubjectWithDomainDto.java
  src/main/java/com/smunity/graduation/domain/graduation/entity/Subject.java
  src/main/java/com/smunity/graduation/domain/graduation/service/GraduationService.java
  src/main/java/com/smunity/graduation/domain/graduation/utils/GraduationUtil.java
Labels: ✨ Feature

#48 [FEATURE] 재학생 인증 API 수정 (#47)
  src/main/java/com/smunity/graduation/domain/auth/dto/AuthResponseDto.java
Labels: ✨ Feature

#53 [STYLE] 추천 과목 로직 주석 추가 + CourseTemporary 삭제 (#50)
  src/main/java/com/smunity/graduation/domain/graduation/controller/GraduationController.java
  src/main/java/com/smunity/graduation/domain/graduation/dto/GraduationResponseDto.java
  src/main/java/com/smunity/graduation/domain/graduation/service/GraduationService.java
  src/main/java/com/smunity/graduation/domain/graduation/utils/GraduationUtil.java
  src/test/java/com/smunity/graduation/domain/graduation/service/GraduationServiceTest.java
Labels: 💄 Style

#55 [FEATURE] 재학생 인증 API 업데이트 (#54)
  build.gradle
  src/main/java/com/smunity/graduation/domain/auth/dto/AuthCourseResponseDto.java
  src/main/java/com/smunity/graduation/domain/auth/dto/AuthResponseDto.java
  src/main/java/com/smunity/graduation/domain/auth/service/AuthService.java
  src/main/java/com/smunity/graduation/global/config/WebClientConfig.java
Labels: ✨ Feature

#57 [BUG] 기이수과목 업로드 API 예외처리 (#56)
  src/main/java/com/smunity/graduation/domain/course/repository/CourseRepository.java
  src/main/java/com/smunity/graduation/domain/course/service/CourseService.java
Labels: 🐛 BugFix

#61 [Feature] 엔티티 학년 & 이수학기 추가
  http/AccountsTest.http
  src/main/java/com/smunity/graduation/domain/accounts/dto/UserRegisterRequestDto.java
  src/main/java/com/smunity/graduation/domain/accounts/dto/UserRegisterResponseDto.java
  src/main/java/com/smunity/graduation/domain/accounts/entity/User.java
  src/main/java/com/smunity/graduation/global/config/SecurityConfig.java
Labels: ✨ Feature
